version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Running static code analysis
      - mvn clean pmd:check
      - echo Packaging the application
      - mvn package
  post_build:
    commands:
      - echo Build completed
artifacts:
  files:
    - target/nciForum.jar
  discard-paths: yes